apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-api-config
data:
  FIRESTORE_PROJECT_ID: {{ .Values.config.FIRESTORE_PROJECT_ID | quote }}
  FIRESTORE_COLLECTION: {{ .Values.config.FIRESTORE_COLLECTION | quote }}
