image:
  repository: ghcr.io/twilight4/api-node
  tag: "0.0.1-24-g33169f0"
  pullPolicy: Always

replicaCount: 2

resources:
  limits:
    cpu: "500m"
    memory: "400Mi"
  requests:
    cpu: "250m"
    memory: "300Mi"

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 50

ingress:
  className: nginx-ingress
  host: ""

config:
  COSMOSDB_DATABASE: "movie-api"
  COSMOSDB_CONTAINER: "reviews"
  COSMOSDB_PARTITION_KEY: "/movieId"
  COSMOSDB_API: "SQL"
