apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
namespace: staging

resources:
  - ../../base/api-node/manifests/

patches:
  - path: ./patches/Deployment.yaml
  - path: ./patches/Hpa.yaml
  - path: ./patches/Ingress.yaml

labels:
  - pairs:
      env: staging

images:
  - name: ghcr.io/twilight4/api-node
    newTag: 0.0.2-130-gdce938e-staging # STAGING_IMAGE_TAG
