apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
namespace: staging

resources:
  - ../../../deploy-services/api-node/manifests/

patches:
  - path: ./patches/Deployment.yaml
  - path: ./patches/Hpa.yaml
#  - path: ./patches/Ingress.yaml      # I don't have a domain

labels:
  - pairs:
      env: staging

images:
  - name: ghcr.io/twilight4/api-node
    newTag: 0.0.2-staging # STAGING_IMAGE_TAG
