apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: {{ .Values.project }}

  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.path }}

  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}

  syncPolicy:
    syncOptions:
{{- range .Values.syncPolicy.syncOptions }}
      - {{ . }}
{{- end }}
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
