image:
  repository: ghcr.io/twilight4/api-node
  tag: 0.0.2 # PRODUCTION_IMAGE_TAG
  pullPolicy: Always

replicaCount: 2

resources:
  limits:
    cpu: "500m"
    memory: "400Mi"
  requests:
    cpu: "250m"
    memory: "300Mi"

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 50

ingress:
  className: gce

config:
  FIRESTORE_PROJECT_ID: "movie-review-platform8451"
  FIRESTORE_COLLECTION: "movies"
