apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
namespace: staging

resources:
  - ../../../deploy-services/movie-api/manifests/
  - ../../../deploy-services/movie-api/namespaces/

patches:
  - path: ./patches/Deployment.yaml
  - path: ./patches/Configmap.yaml
  - path: ./patches/Hpa.yaml

labels:
  - pairs:
      env: staging

images:
  - name: ghcr.io/twilight4/api-node
    newTag: 0.0.1-61-g9785050-staging # STAGING_IMAGE_TAG
