apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - movie-api-deployment.yaml
  - movie-api-service.yaml
  - movie-api-hpa.yaml
  - ingress.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - netpol.yaml
