name: movie-api-argo-application
argocdNamespace: argocd
project: default
namePrefix: staging-

labels:
  env: staging

source:
  repoURL: https://github.com/Twilight4/movie-review-platform.git
  targetRevision: HEAD
  path: k8s/overlays/staging

destination:
  server: https://kubernetes.default.svc
  namespace: staging

syncPolicy:
  syncOptions:
    - CreateNamespace=True
  automated:
    prune: true
    selfHeal: true

