name: movie-api-argo-application
argocdNamespace: argocd
project: default

source:
  repoURL: https://github.com/Twilight4/movie-review-platform.git
  targetRevision: HEAD
  path: k8s/overlays/production

destination:
  server: https://kubernetes.default.svc
  namespace: production

syncPolicy:
  syncOptions:
    - CreateNamespace=True
  automated: {}
