namePrefix: staging-

labels:
  env: staging

image:
  repository: ghcr.io/twilight4/api-node
  tag: 0.0.1-61-g9785050-staging # STAGING_IMAGE_TAG
  pullPolicy: Always

replicaCount: 1

env:
  - name: NODE_ENV
    value: staging
  - name: LOG_LEVEL
    value: debug

resources:
  limits:
    cpu: "500m"
    memory: "400Mi"
  requests:
    cpu: "250m"
    memory: "300Mi"

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50

ingress:
  className: nginx-ingress
  host: ""

config:
  COSMOSDB_DATABASE: "movie-api-staging"
  COSMOSDB_CONTAINER: "reviews"
  COSMOSDB_PARTITION_KEY: "/movieId"
  COSMOSDB_API: "SQL"
