apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../deploy-services/movie-api/manifests/
  - ../../../deploy-services/movie-api/namespaces/

patches:
  - path: ./patches/Deployment.yaml

images:
  - name: ghcr.io/twilight4/api-node
    newTag: 0.0.1-49-g97a530e # PRODUCTION_IMAGE_TAG
