apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../../deploy-services/api-node/manifests/

patches:
  - path: ./patches/Deployment.yaml
#  - path: ./patches/Ingress.yaml     # I don't have a domain

images:
  - name: ghcr.io/twilight4/api-node
    newTag: 0.0.2 # PRODUCTION_IMAGE_TAG
