name: ci-workflow

on:
  push:
    branches: ["main"]
    tags: "[0-9]*.[0-9]*.[0-9]*"
    paths:
      # only rebuild when app code changes
      - "app/**/*"
      # exclude these files
      - "!app/README.md"
      - "!app/Taskfile.yaml"
      - "!app/api-node/Taskfile.yaml"
  workflow_dispatch:

jobs:
  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag }}     # the image tag itself
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Necessary to get all tags for IMAGE_TAG generation with git describe
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Generate Image Tag
        id: generate-image-tag
        working-directory: cicd/github-actions
        run: |
          image_tag=$(task generate-version-tag)
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

      - name: Generate Image Tag for production
        id: generate-image-tag-prod
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: cicd/github-actions
        run: |
          image_tag_prod=$(task generate-version-tag-prod)
          echo "image_tag_prod=$image_tag_prod" >> $GITHUB_OUTPUT

  build-tag-push:
    runs-on: ubuntu-latest
    needs: generate-image-tag

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push staging image
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        working-directory: cicd/github-actions
        run: |
          task build-push-container-image-multi-arch IMAGE_TAG=${IMAGE_TAG}-staging

      - name: Build and push production image
        if: startsWith(github.ref, 'refs/tags/')
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag-prod.outputs.image_tag_prod }}
        working-directory: cicd/github-actions
        run: |
          task build-push-container-image-multi-arch IMAGE_TAG=${IMAGE_TAG}

  update-tags:
    runs-on: ubuntu-latest
    needs: [generate-image-tag, build-tag-push]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Update Image Tags
        working-directory: cicd/github-actions
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        run: |
          # Update staging tags for push to main or release a tag
          task update-staging-image-tags NEW_TAG=${IMAGE_TAG}-staging

          # Update production tags only for release tags
          if [[ $GITHUB_REF == refs/tags/*.*.* ]]; then
            task update-production-image-tags NEW_TAG=${IMAGE_TAG}
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.9
        with:
          base: main
          token: ${{ secrets.PR_ACTION }}
          title: "Update image tags to (${{ needs.generate-image-tag.outputs.image_tag }})"
