name: image-ci

on:
  push:
    branches: ["main"]
    tags: "[0-9]*.[0-9]*.[0-9]*"
    paths:
      - "app/**/*"  # only rebuild when app code changes

jobs:
  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag }}     # the image tag itself
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Necessary to get all tags for IMAGE_TAG generation with git describe
          fetch-depth: 0

      # Install task
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      # Generate image tag
      - name: Generate Image Tag
        id: generate-image-tag
        working-directory: .github/actions
        run: |
          image_tag=$(task generate-version-tag)
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
